import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export default async function handler(req, res) {
    if (req.method !== 'POST') {
          return res.status(405).json({ error: 'Method not allowed' });
    }

  const { name, email } = req.body;

  if (!name || !email) {
        return res.status(400).json({ error: 'Name and email are required' });
  }

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
          return res.status(400).json({ error: 'Invalid email address' });
    }

  try {
        await resend.emails.send({
                from: 'FitPlus <onboarding@resend.dev>',
                to: email,
                subject: 'Welcome to the FitPlus AI Waitlist! 🚀',
                html: `
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                      <title>Welcome to FitPlus AI</title>
                      </head>
                      <body style="margin:0;padding:0;background:#0a0a0a;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#f0f0f0;">
                        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0a0a0a;padding:40px 0;">
                            <tr>
                                  <td align="center">
                                          <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;border-radius:16px;overflow:hidden;border:1px solid rgba(255,255,255,0.08);">

                                                    <!-- Header -->
                                                              <tr>
                                                                          <td style="background:linear-gradient(135deg,#0d0d0d 0%,#1a1a2e 50%,#16213e 100%);padding:32px 40px 28px;text-align:center;">
                                                                                        <p style="margin:0 0 12px;font-size:28px;font-weight:800;color:#ffffff;letter-spacing:1px;">
                                                                                                        🏃 FitPlus AI
                                                                                                                      </p>
                                                                                                                                    <div style="width:60px;height:3px;background:linear-gradient(90deg,#00c8ff,#7b2fff);margin:0 auto;border-radius:99px;"></div>
                                                                                                                                                </td>
                                                                                                                                                          </tr>
                                                                                                                                                          
                                                                                                                                                                    <!-- Body -->
                                                                                                                                                                              <tr>
                                                                                                                                                                                          <td style="background:#111111;padding:40px 40px 32px;">
                                                                                                                                                                                                        <h1 style="margin:0 0 8px;font-size:28px;font-weight:800;color:#ffffff;">
                                                                                                                                                                                                                        Hi ${name}! 🎉
                                                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                                                                    <p style="margin:0 0 24px;font-size:20px;font-weight:700;color:#7b6cff;">
                                                                                                                                                                                                                                                                    You're officially on the FitPlus AI waitlist!
                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                <p style="margin:0 0 20px;font-size:16px;line-height:1.7;color:#cccccc;">
                                                                                                                                                                                                                                                                                                                Thank you for joining us on this exciting journey. FitPlus AI is redefining fitness with personalized AI coaching, smart nutrition plans, and wearable integration — all adapting to <em>your</em> body in real time.
                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                            <p style="margin:0 0 20px;font-size:16px;line-height:1.7;color:#cccccc;">
                                                                                                                                                                                                                                                                                                                                                            As a waitlist member, you'll get:
                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                        <table cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px;">
                                                                                                                                                                                                                                                                                                                                                                                                        <tr><td style="padding:4px 0;font-size:15px;color:#cccccc;">✅&nbsp; <strong style="color:#ffffff;">Early access</strong> before public launch</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                        <tr><td style="padding:4px 0;font-size:15px;color:#cccccc;">✅&nbsp; <strong style="color:#ffffff;">30-day free Pro</strong> trial</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr><td style="padding:4px 0;font-size:15px;color:#cccccc;">✅&nbsp; <strong style="color:#ffffff;">Special launch discount</strong></td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style="margin:0 0 32px;font-size:15px;color:#888888;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    We'll be in touch soon. Get ready to train smarter. 💪
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <table cellpadding="0" cellspacing="0" border="0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style="background:linear-gradient(90deg,#ff3b30,#ff6b35);border-radius:9999px;padding:14px 36px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style="font-size:15px;font-weight:700;color:#ffffff;letter-spacing:0.5px;">Launch Date: June 2026 🚀</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <!-- Footer -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td style="background:#0d0d0d;padding:24px 40px;text-align:center;border-top:1px solid rgba(255,255,255,0.06);">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style="margin:0 0 6px;font-size:13px;color:#555555;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          © 2026 FitPlus AI. All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style="margin:0;font-size:12px;color:#444444;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      You're receiving this because you signed up at fitplus-landing-page.vercel.app
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `,
        });

      return res.status(200).json({ success: true });
  } catch (error) {
        console.error('Resend error:', error);
        return res.status(500).json({ error: 'Failed to send email' });
  }
}
